create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_ctrl_logic/curr_state[0]} {u_ctrl_logic/curr_state[1]} {u_ctrl_logic/curr_state[2]} {u_ctrl_logic/curr_state[3]} {u_ctrl_logic/curr_state[4]} {u_ctrl_logic/curr_state[5]} {u_ctrl_logic/curr_state[6]} {u_ctrl_logic/curr_state[7]} {u_ctrl_logic/curr_state[8]} {u_ctrl_logic/curr_state[9]} {u_ctrl_logic/curr_state[10]} {u_ctrl_logic/curr_state[11]} {u_ctrl_logic/curr_state[12]} {u_ctrl_logic/curr_state[13]} {u_ctrl_logic/curr_state[14]} {u_ctrl_logic/curr_state[15]} {u_ctrl_logic/curr_state[16]} {u_ctrl_logic/curr_state[17]} {u_ctrl_logic/curr_state[18]} {u_ctrl_logic/curr_state[19]} {u_ctrl_logic/curr_state[20]} {u_ctrl_logic/curr_state[21]} {u_ctrl_logic/curr_state[22]} {u_ctrl_logic/curr_state[23]} {u_ctrl_logic/curr_state[24]} {u_ctrl_logic/curr_state[25]} {u_ctrl_logic/curr_state[26]} {u_ctrl_logic/curr_state[27]} {u_ctrl_logic/curr_state[28]} {u_ctrl_logic/curr_state[29]} {u_ctrl_logic/curr_state[30]} {u_ctrl_logic/curr_state[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_ctrl_logic/byte_counter[0]} {u_ctrl_logic/byte_counter[1]} {u_ctrl_logic/byte_counter[2]} {u_ctrl_logic/byte_counter[3]} {u_ctrl_logic/byte_counter[4]} {u_ctrl_logic/byte_counter[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_ctrl_logic/addr_q[0]} {u_ctrl_logic/addr_q[1]} {u_ctrl_logic/addr_q[2]} {u_ctrl_logic/addr_q[3]} {u_ctrl_logic/addr_q[4]} {u_ctrl_logic/addr_q[5]} {u_ctrl_logic/addr_q[6]} {u_ctrl_logic/addr_q[7]} {u_ctrl_logic/addr_q[8]} {u_ctrl_logic/addr_q[9]} {u_ctrl_logic/addr_q[10]} {u_ctrl_logic/addr_q[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_ctrl_logic/op_type_q[0]} {u_ctrl_logic/op_type_q[1]} {u_ctrl_logic/op_type_q[2]} {u_ctrl_logic/op_type_q[3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
